"""Temporary connectivity test script for Google Sheets.

Loads the token generated by generate_drive_token.py,
authenticates via google.oauth2.credentials.Credentials,
builds a Sheets v4 service, and opens a specific spreadsheet.
"""

from __future__ import annotations

import json
import os
import sys

# Allow running directly via python backend/utils/<script>.py
_current = os.path.dirname(os.path.abspath(__file__))
_backend_dir = os.path.dirname(_current)
if _backend_dir not in sys.path:
    sys.path.insert(0, _backend_dir)

from googleapiclient.discovery import build

from config.google_config import config as google_config
from services.google_auth_service import GoogleAuthService


from sheets_utils import _get_client, _open_spreadsheet

def main() -> None:
    try:
        client = _get_client()
        spreadsheet = _open_spreadsheet(client)
        if spreadsheet:
            print("Connection Successful")
            print(f"Spreadsheet Title: {spreadsheet.title}")
            print(f"Spreadsheet ID: {spreadsheet.id}")
        else:
            print("Error: Could not open spreadsheet", file=sys.stderr)
            sys.exit(1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
